### ISSUE TITLE
Hallo, ich bin mit Teilnehmer

### ISSUE THREAD

**Issue by Raphael2b3** [leonhma/bwinf-40-2#1]
Ich habe zufällig genau die selben aufgaben im bwinf behandelt, habe es aber leider nicht in die dritte runde geschafft. Ich wollte fragen ob du es in die dritte runde geschafft hast. LG Raphael

**Comment by leonhma** [comment]
Hi. Ne hab ich leider nicht. Größtenteils war die Laufzeit bei den größeren Beispielen einfach zu schlecht.
